using System.Collections;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Windows;
using CashierPOS.Core;
using CashierPOS.Application;
using CashierPOS.Infrastructure;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Logging;
namespace CashierPOS.WPF;
public sealed record Nav(string Key,string Title,string Permission);
public sealed record ActionButton(string Key,string Title);
public sealed record Stat(string Title,string Value);
public sealed record Bar(string Label,double Width,string Amount);
public sealed record ProductRow(long Id,string SKU,string Barcode,string Name,decimal Price,decimal? Cost,int Stock,int MinimumStock,bool IsActive);
public sealed record SaleRow(long Id,string Invoice,DateTime Date,long CashierId,decimal Total,decimal Discount,decimal Tax);
public sealed record ItemRow(long Id,string Name,int Quantity,decimal Price,decimal Discount,decimal Tax,decimal Total);
public sealed record PurchaseRow(long Id,long PurchaseId,long ProductId,int Ordered,int Received,decimal UnitCost);
public sealed record ShiftRow(long Id,long UserId,DateTime Opened,DateTime? Closed,decimal Opening,decimal? Expected,decimal? Counted,decimal? Difference,string Notes);
public sealed record MovementRow(long Id,long ProductId,string Type,int QuantityChange,int BeforeQuantity,int AfterQuantity,long UserId,string Reason,DateTime Date);
public sealed record ExpenseRow(long Id,string Category,string Description,decimal Amount,long UserId,DateTime Date);
public sealed record SettingRow(string Key,string Value);
public partial class CartRow:ObservableObject {
 public long ProductId{get;init;}public string Name{get;init;}="";public long BaseUnitCents{get;init;}public bool IsPriceOverride{get;set;}[ObservableProperty] private long unitCents;partial void OnUnitCentsChanged(long value){OnPropertyChanged(nameof(Price));OnPropertyChanged(nameof(Total));}public decimal Price=>Money.Amount(UnitCents);
 [ObservableProperty] private int quantity=1;public decimal Total=>Price*Quantity;partial void OnQuantityChanged(int value)=>OnPropertyChanged(nameof(Total));
}
public partial class MainViewModel:ObservableObject {
 private readonly SecurityService security;private readonly PosService pos;private readonly ExcelService excel;private readonly BackupService backup;private readonly IDbFactory factory;private readonly DialogService dialogs;private readonly PrintService printing;private readonly ILogger<MainViewModel> logger;private readonly SemaphoreSlim gate=new(1,1);private Dictionary<string,string> settings=[];private Report? currentReport;private Guid requestId=Guid.NewGuid();private long? shownSaleId;private DateTime lastBackupAttempt=DateTime.UtcNow;
 public Session Session{get;private set;}public event Action? EndSession;
 public Texts L{get;private set;}=new(false);public string StoreName=>settings.GetValueOrDefault("StoreName","CashierPOS");public string UserLabel=>$"{Session.FullName} • {(Session.IsManager?"Manager":"Employee")}";public string Currency=>settings.GetValueOrDefault("Currency","EGP");
 public FlowDirection Direction=>settings.GetValueOrDefault("Language")=="ar"?FlowDirection.RightToLeft:FlowDirection.LeftToRight;
 public ObservableCollection<Nav> Navigation{get;}=[];public ObservableCollection<ActionButton> Actions{get;}=[];public ObservableCollection<CartRow> Cart{get;}=[];public ObservableCollection<Stat> Stats{get;}=[];public ObservableCollection<Bar> Bars{get;}=[];
 [ObservableProperty] private Nav? selectedNav;[ObservableProperty] private IList rows=new List<object>();[ObservableProperty] private object? selectedRow;[ObservableProperty] private List<ProductRow> searchResults=[];[ObservableProperty] private ProductRow? selectedProduct;[ObservableProperty] private CartRow? selectedCart;
 [ObservableProperty] private string search="";[ObservableProperty] private string status="Ready / جاهز";[ObservableProperty] private bool busy;[ObservableProperty] private string discount="0";[ObservableProperty] private string cash="0";[ObservableProperty] private string card="0";[ObservableProperty] private string customerId="";[ObservableProperty] private string notes="";
 [ObservableProperty] private decimal subtotal;[ObservableProperty] private decimal tax;[ObservableProperty] private decimal grandTotal;[ObservableProperty] private decimal change;
 [ObservableProperty] private DateTime fromDate=DateTime.Today;[ObservableProperty] private DateTime throughDate=DateTime.Today;
 public bool Ready=>!Busy;public bool IsPos=>SelectedNav?.Key=="pos";public bool IsDashboard=>SelectedNav?.Key=="dashboard";public bool IsTable=>!IsPos&&!IsDashboard;public bool ShowDates=>SelectedNav?.Key is "dashboard" or "reports" or "sales";
 public MainViewModel(Session session,SecurityService security,PosService pos,ExcelService excel,BackupService backup,IDbFactory factory,DialogService dialogs,PrintService printing,ILogger<MainViewModel> logger){Session=session;this.security=security;this.pos=pos;this.excel=excel;this.backup=backup;this.factory=factory;this.dialogs=dialogs;this.printing=printing;this.logger=logger;Cart.CollectionChanged+=(_,_)=>Recalculate();LoadPreferences();SelectedNav=Navigation.FirstOrDefault();}
 private bool Can(string permission)=>security.Can(Session,permission);
 private void LoadPreferences(){settings=pos.Settings(Session);L=new Texts(settings.GetValueOrDefault("Language")=="ar");OnPropertyChanged(nameof(L));OnPropertyChanged(nameof(StoreName));OnPropertyChanged(nameof(Currency));OnPropertyChanged(nameof(Direction));ApplyTheme(settings.GetValueOrDefault("Theme")=="dark");Navigation.Clear();
  (string key,string name,string permission)[] navs=[("dashboard","Dashboard","Reports.ViewOwn"),("pos","Point of Sale","Sales.Create"),("products","Products","Products.View"),("categories","Categories","Products.View"),("inventory","Inventory","Inventory.View"),("purchases","Purchases","Purchases.Manage"),("suppliers","Suppliers","Suppliers.Manage"),("customers","Customers","Customers.View"),("sales","Sales History","Sales.ViewOwn"),("expenses","Expenses","Expenses.View"),("reports","Reports","Reports.ViewOwn"),("shifts","Shifts","Shifts.Own"),("users","Employees","Users.Manage"),("permissions","Roles & Permissions","Permissions.Manage"),("excel","Excel Import/Export","Excel.Import"),("backup","Backup & Restore","Backup.Create"),("settings","Settings","Settings.Manage"),("audit","Audit Logs","AuditLogs.View")];foreach(var n in navs)if(Can(n.permission)||n.key=="excel"&&Can("Excel.Export"))Navigation.Add(new Nav(n.key,L[n.name],n.permission));}
 private static void ApplyTheme(bool dark){var resources=System.Windows.Application.Current.Resources;foreach(var (key,color) in new Dictionary<string,string>{{"BackgroundBrush",dark?"#121B2A":"#F3F5F9"},{"SurfaceBrush",dark?"#1B283D":"#FFFFFF"},{"TextBrush",dark?"#F1F5FC":"#162238"},{"MutedBrush",dark?"#ADBCD3":"#586780"},{"BorderBrush",dark?"#34445E":"#DCE2ED"}})resources[key]=new System.Windows.Media.SolidColorBrush((System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString(color));}
 partial void OnSelectedNavChanged(Nav? value){OnPropertyChanged(nameof(IsPos));OnPropertyChanged(nameof(IsDashboard));OnPropertyChanged(nameof(IsTable));OnPropertyChanged(nameof(ShowDates));SelectedRow=null;shownSaleId=null;_ = RefreshAsync();}
 partial void OnBusyChanged(bool value)=>OnPropertyChanged(nameof(Ready));
 partial void OnDiscountChanged(string value)=>Recalculate();partial void OnCashChanged(string value)=>Recalculate();partial void OnCardChanged(string value)=>Recalculate();
 private async Task Run(Func<Task> action){await gate.WaitAsync();Busy=true;try{await action();}catch(Exception e){Status=e is DomainException or FormatException or OverflowException?e.Message:"Operation failed. Check the application log.";logger.LogWarning(e,"POS operation failed");}finally{Busy=false;gate.Release();}}
 [RelayCommand] private Task RefreshAsync()=>Run(Load);
 private async Task Load(){if(SelectedNav==null)return;var key=SelectedNav.Key;Actions.Clear();AddAction("refresh","Refresh");IList newRows=new List<object>();
  switch(key){
   case "pos":SearchResults=await Task.Run(()=>pos.Products(Session,Search).Select(ProductDisplay).ToList());return;
   case "products":newRows=await Task.Run(()=>pos.Products(Session,"",true).Select(ProductDisplay).ToList());AddAllowed("product.add","Add","Products.Create");AddAllowed("product.edit","Edit","Products.Edit");AddAllowed("product.archive","Archive","Products.Archive");break;
   case "categories":newRows=await Task.Run(()=>pos.Categories(Session));AddAllowed("category.add","Add","Products.Edit");break;
   case "inventory":newRows=await Task.Run(()=>pos.Movements(Session).Select(x=>new MovementRow(x.Id,x.ProductId,x.Type,x.QuantityChange,x.BeforeQuantity,x.AfterQuantity,x.UserId,x.Reason,x.CreatedAtUtc.ToLocalTime())).ToList());AddAction("inventory.adjust","Adjust stock");break;
   case "purchases":newRows=await Task.Run(()=>pos.PurchaseItems(Session).Select(x=>new PurchaseRow(x.Id,x.PurchaseId,x.ProductId,x.Ordered,x.Received,Money.Amount(x.UnitCostCents))).ToList());AddAction("purchase.add","Add");AddAction("purchase.receive","Receive stock");break;
   case "customers":newRows=await Task.Run(()=>pos.Customers(Session));AddAllowed("customer.add","Add","Customers.Create");AddAllowed("customer.edit","Edit","Customers.Edit");break;
   case "suppliers":newRows=await Task.Run(()=>pos.Suppliers(Session));AddAction("supplier.add","Add");AddAction("supplier.edit","Edit");break;
   case "expenses":newRows=await Task.Run(()=>pos.Expenses(Session).Select(x=>new ExpenseRow(x.Id,x.Category,x.Description,Money.Amount(x.AmountCents),x.UserId,x.CreatedAtUtc.ToLocalTime())).ToList());AddAllowed("expense.add","Add","Expenses.Create");break;
   case "dashboard":case "reports":case "sales":currentReport=await Task.Run(()=>pos.Report(Session,FromDate.Date.ToUniversalTime(),ThroughDate.Date.AddDays(1).ToUniversalTime()));newRows=currentReport.Sales.Select(x=>new SaleRow(x.Id,x.InvoiceNumber,x.CreatedAtUtc.ToLocalTime(),x.UserId,Money.Amount(x.TotalCents),Money.Amount(x.DiscountCents),Money.Amount(x.TaxCents))).ToList();UpdateStats(currentReport);if(key=="sales"){AddAction("sale.items","Sale items");AddAllowed("sale.print","Print","Receipts.Print");}if(key=="reports"){AddAllowed("report.export","Export sales","Excel.Export");AddAction("report.print","Print");}if(key=="dashboard")await LoadBars();break;
   case "shifts":newRows=await Task.Run(()=>pos.Shifts(Session).Select(x=>new ShiftRow(x.Id,x.UserId,x.OpenedAtUtc.ToLocalTime(),x.ClosedAtUtc?.ToLocalTime(),Money.Amount(x.OpeningCents),x.ExpectedCents is long a?Money.Amount(a):null,x.CountedCents is long b?Money.Amount(b):null,x.CountedCents is long c&&x.ExpectedCents is long d?Money.Amount(c-d):null,x.Notes)).ToList());AddAction("shift.open","Open shift");AddAction("shift.close","Close shift");AddAction("shift.cash","Cash in / out");AddAction("shift.print","Print");break;
   case "users":case "permissions":newRows=await Task.Run(()=>security.Users(Session));if(key=="users"){AddAction("user.add","Add");AddAction("user.active","Activate / deactivate");AddAction("user.reset","Reset password");}else AddAction("user.permissions","Configure permissions");break;
   case "excel":if(Can("Excel.Import")){AddAction("excel.template","Template");AddAction("excel.import","Import");}AddAllowed("excel.export","Export inventory","Excel.Export");newRows=new List<object>();break;
   case "backup":newRows=await Task.Run(()=>{using var db=factory.Open();security.Require(db,Session,"Backup.Create");return db.Set<BackupHistory>().OrderByDescending(x=>x.Id).Take(100).ToList();});AddAction("backup.create","Backup");AddAction("backup.restore","Restore");break;
   case "settings":newRows=settings.Select(x=>new SettingRow(x.Key,x.Value)).ToList();AddAction("setting.save","Save setting");break;
   case "audit":newRows=await Task.Run(()=>pos.Audit(Session));break;
  }
  Rows=newRows;Status=$"{SelectedNav.Title} • {Rows.Count} rows / سجل";
 }
 private static ProductRow ProductDisplay(ProductView p)=>new(p.Id,p.SKU,p.Barcode,p.Name,Money.Amount(p.PriceCents),p.CostCents is long c?Money.Amount(c):null,p.Stock,p.MinimumStock,p.IsActive);
 private void AddAction(string key,string title)=>Actions.Add(new ActionButton(key,L[title]));private void AddAllowed(string key,string title,string permission){if(Can(permission))AddAction(key,title);}
 private void UpdateStats(Report r){Stats.Clear();Stats.Add(new Stat(L["Sales"],Money.Text(r.SalesCents)+" "+Currency));Stats.Add(new Stat(L["Refunds"],Money.Text(r.RefundCents)+" "+Currency));Stats.Add(new Stat(L["Revenue excl. tax"],Money.Text(r.NetRevenueCents)+" "+Currency));Stats.Add(new Stat(L["Tax"],Money.Text(r.TaxCents)+" "+Currency));Stats.Add(new Stat(L["Low stock"],r.LowStock.ToString()));if(r.GrossProfitCents is long gross)Stats.Add(new Stat(L["Gross profit"],Money.Text(gross)+" "+Currency));if(r.NetProfitCents is long net)Stats.Add(new Stat(L["Net profit estimate"],Money.Text(net)+" "+Currency));}
 private async Task LoadBars(){var values=await Task.Run(()=>Enumerable.Range(0,7).Select(i=>{var day=DateTime.Today.AddDays(i-6);var r=pos.Report(Session,day.ToUniversalTime(),day.AddDays(1).ToUniversalTime());return(day,r.NetRevenueCents);}).ToList());var max=Math.Max(1,values.Max(x=>x.NetRevenueCents));Bars.Clear();foreach(var (day,amount) in values)Bars.Add(new Bar(day.ToString("dd/MM"),Math.Max(0,amount)*440d/max,Money.Text(amount)));}
 [RelayCommand] private Task FindAsync()=>Run(async()=>SearchResults=await Task.Run(()=>pos.Products(Session,Search).Select(ProductDisplay).ToList()));
 [RelayCommand] private void AddProduct(){if(SelectedProduct==null)return;AddToCart(SelectedProduct,1);Search="";}
 public async Task Scan(){await FindAsync();var match=SearchResults.FirstOrDefault(x=>x.Barcode==Search||x.SKU.Equals(Search,StringComparison.OrdinalIgnoreCase));if(match!=null){SelectedProduct=match;AddProduct();}else if(SearchResults.Count==1){SelectedProduct=SearchResults[0];AddProduct();}}
 private void AddToCart(ProductRow product,int qty){var old=Cart.SingleOrDefault(x=>x.ProductId==product.Id);if(old!=null)old.Quantity+=qty;else{var c=new CartRow{ProductId=product.Id,Name=product.Name,BaseUnitCents=Money.Cents(product.Price),UnitCents=Money.Cents(product.Price),Quantity=qty};c.PropertyChanged+=(_,e)=>{if(e.PropertyName is nameof(CartRow.Quantity) or nameof(CartRow.UnitCents))Recalculate();};Cart.Add(c);}Recalculate();}
 [RelayCommand] private void RemoveItem(){if(SelectedCart!=null)Cart.Remove(SelectedCart);}
 [RelayCommand] private void ClearCart(){if(Cart.Count==0||dialogs.Confirm("Clear the current cart? / مسح السلة؟"))ResetCart();}
 private static CartLine ToCartLine(CartRow x)=>new(x.ProductId,x.Quantity,x.IsPriceOverride?x.UnitCents:null,x.BaseUnitCents);
 [RelayCommand] private void DiscountDialog(){var f=dialogs.Form("Discount / خصم",new Field("type","Type / النوع",Choices:["Fixed amount","Percentage"]),new Field("value","Value / القيمة"));if(f==null)return;try{var amount=D(f["value"]);if(amount<0||f["type"]=="Percentage"&&amount>100)throw new DomainException("Invalid discount.");Discount=(f["type"]=="Percentage"?Money.Amount(Money.Cents(Subtotal*amount/100m)):amount).ToString(CultureInfo.InvariantCulture);}catch(DomainException ex){Status=ex.Message;}}
 [RelayCommand] private void OverridePrice(){if(SelectedCart==null){Status="Select a cart item first.";return;}var f=dialogs.Form("Override price / تعديل سعر داخل الفاتورة",new Field("price","Unit price / سعر الوحدة",SelectedCart.Price.ToString(CultureInfo.InvariantCulture)));if(f==null)return;try{var amount=D(f["price"]);if(amount<0)throw new DomainException("Price cannot be negative.");SelectedCart.IsPriceOverride=true;SelectedCart.UnitCents=Money.Cents(amount);Recalculate();}catch(DomainException ex){Status=ex.Message;}}
 private void ResetCart(){Cart.Clear();Discount="0";Cash="0";Card="0";CustomerId="";Notes="";requestId=Guid.NewGuid();Recalculate();}
 private void Recalculate(){try{var items=Cart.Select(x=>new SaleItem{Quantity=x.Quantity,UnitPriceCents=x.UnitCents}).ToList();Subtotal=items.Sum(x=>Money.Amount(x.UnitPriceCents)*x.Quantity);if(items.Count==0){Tax=GrandTotal=Change=0;return;}if(items.Any(x=>x.Quantity<=0))throw new DomainException("Cart quantities must be positive whole numbers.");var result=PosService.Calculate(items,Money.Cents(D(Discount)),D(settings.GetValueOrDefault("TaxPercent","0")),settings.GetValueOrDefault("TaxInclusive")=="true");Tax=Money.Amount(result.Tax);GrandTotal=Money.Amount(result.Total);Change=Math.Max(0,D(Cash)+D(Card)-GrandTotal);}catch(Exception e) when(e is FormatException or DomainException or OverflowException){Tax=GrandTotal=Change=0;Status=e.Message;}}
 [RelayCommand] private Task CompleteAsync()=>Run(async()=>{if(Cart.Count==0)throw new DomainException("Cart is empty.");var input=new Checkout(requestId,Cart.Select(ToCartLine).ToList(),Money.Cents(D(Discount)),[new Tender("Cash",Money.Cents(D(Cash))),new Tender("Card",Money.Cents(D(Card)))],string.IsNullOrWhiteSpace(CustomerId)?null:long.Parse(CustomerId),Notes);var receipt=await Task.Run(()=>pos.Checkout(Session,input));ResetCart();Status=$"Saved {receipt.Sale.InvoiceNumber}; change / الباقي: {Money.Text(receipt.Sale.ChangeCents)} {Currency}";if(dialogs.Confirm("Sale saved. Print receipt? / البيع اتحفظ. طباعة الإيصال؟"))printing.Receipt(receipt,settings);SearchResults=await Task.Run(()=>pos.Products(Session).Select(ProductDisplay).ToList());});
 [RelayCommand] private Task SuspendAsync()=>Run(async()=>{var f=dialogs.Form("Suspend sale / تعليق بيع",new Field("name","Label / اسم السلة"));if(f==null)return;var lines=Cart.Select(ToCartLine).ToList();await Task.Run(()=>pos.Suspend(Session,f["name"],lines));ResetCart();Status="Cart suspended / تم تعليق السلة";});
 [RelayCommand] private Task ResumeAsync()=>Run(async()=>{if(Cart.Count>0)throw new DomainException("Clear or suspend the active cart first.");var suspended=await Task.Run(()=>pos.Suspended(Session));if(suspended.Count==0)throw new DomainException("No suspended carts.");var choices=suspended.Select(x=>$"{x.Id} | {x.Name} | {x.CreatedAtUtc.ToLocalTime():g}").ToArray();var f=dialogs.Form("Resume / استئناف",new Field("id","Suspended sale / السلة",Choices:choices));if(f==null)return;var id=ChoiceId(f["id"]);var products=await Task.Run(()=>pos.Products(Session));var preview=suspended.Single(x=>x.Id==id);var saved=System.Text.Json.JsonSerializer.Deserialize<List<CartLine>>(preview.CartJson)??[];if(saved.Any(x=>!products.Any(p=>p.Id==x.ProductId)))throw new DomainException("A suspended product was archived. Ask a manager to reactivate it.");var lines=await Task.Run(()=>pos.Resume(Session,id));foreach(var c in lines)AddToCart(ProductDisplay(products.Single(p=>p.Id==c.ProductId)),c.Quantity);requestId=Guid.NewGuid();Status="Cart resumed; current prices and stock will be checked at checkout.";});
 [RelayCommand] private Task ActionAsync(string key)=>Run(async()=>{
  Dictionary<string,string>? f;var selected=SelectedRow;
  switch(key){
   case "refresh":await Load();return;
   case "product.add":case "product.edit":var p=key=="product.edit"?selected as ProductRow:null;if(key=="product.edit"&&p==null)throw new DomainException("Select a product.");f=dialogs.Form("Product / المنتج",new Field("sku","SKU / كود المنتج",p?.SKU??""),new Field("barcode","Barcode / الباركود",p?.Barcode??""),new Field("name","Name / الاسم",p?.Name??""),new Field("cost","Cost / التكلفة",(p?.Cost??0).ToString(CultureInfo.InvariantCulture)),new Field("price","Price / سعر البيع",(p?.Price??0).ToString(CultureInfo.InvariantCulture)),new Field("minimum","Minimum stock / الحد الأدنى",(p?.MinimumStock??0).ToString()));if(f==null)return;var product=new ProductInput(p?.Id??0,f["sku"],f["barcode"],f["name"],D(f["cost"]),D(f["price"]),int.Parse(f["minimum"]));await Task.Run(()=>pos.SaveProduct(Session,product));break;
   case "product.archive":if(selected is not ProductRow archive)throw new DomainException("Select a product.");if(!dialogs.Confirm("Archive product? Existing financial records will be preserved. / أرشفة المنتج؟"))return;await Task.Run(()=>pos.ArchiveProduct(Session,archive.Id));break;
   case "category.add":f=dialogs.Form("Category / القسم",new Field("name","Name / الاسم"));if(f==null)return;await Task.Run(()=>pos.AddCategory(Session,f["name"]));break;
   case "inventory.adjust":var invProducts=await Task.Run(()=>pos.Products(Session));f=dialogs.Form("Stock adjustment / تسوية مخزون",new Field("product","Product / المنتج",Choices:invProducts.Select(x=>$"{x.Id} | {x.Name} | stock: {x.Stock}").ToArray()),new Field("delta","Quantity change (+ / -) / فرق الكمية"),new Field("reason","Reason / السبب"));if(f==null)return;await Task.Run(()=>pos.AdjustStock(Session,ChoiceId(f["product"]),int.Parse(f["delta"]),f["reason"]));break;
   case "supplier.add":case "supplier.edit":var supplier=key.EndsWith("edit")?selected as Supplier:null;if(key.EndsWith("edit")&&supplier==null)throw new DomainException("Select a supplier.");f=ContactForm("Supplier / المورد",supplier?.Name,supplier?.Phone,supplier?.Notes);if(f==null)return;await Task.Run(()=>pos.SaveSupplier(Session,supplier?.Id??0,f["name"],f["phone"],f["notes"]));break;
   case "customer.add":case "customer.edit":var customer=key.EndsWith("edit")?selected as Customer:null;if(key.EndsWith("edit")&&customer==null)throw new DomainException("Select a customer.");f=ContactForm("Customer / العميل",customer?.Name,customer?.Phone,customer?.Notes);if(f==null)return;await Task.Run(()=>pos.SaveCustomer(Session,customer?.Id??0,f["name"],f["phone"],f["notes"]));break;
   case "purchase.add":var suppliers=await Task.Run(()=>pos.Suppliers(Session));var products=await Task.Run(()=>pos.Products(Session));if(suppliers.Count==0||products.Count==0)throw new DomainException("Create a supplier and a product first.");f=dialogs.Form("Purchase order / أمر شراء",new Field("supplier","Supplier / المورد",Choices:suppliers.Select(x=>$"{x.Id} | {x.Name}").ToArray()),new Field("product","Product / المنتج",Choices:products.Select(x=>$"{x.Id} | {x.Name}").ToArray()),new Field("qty","Ordered quantity / الكمية"),new Field("cost","Unit cost / تكلفة الوحدة"),new Field("invoice","Supplier invoice / فاتورة المورد"));if(f==null)return;await Task.Run(()=>pos.CreatePurchase(Session,ChoiceId(f["supplier"]),f["invoice"],[new PurchaseLine(ChoiceId(f["product"]),int.Parse(f["qty"]),Money.Cents(D(f["cost"])))]));break;
   case "purchase.receive":if(selected is not PurchaseRow purchase)throw new DomainException("Select a purchase item.");f=dialogs.Form("Receive / استلام",new Field("qty","Quantity / الكمية",(purchase.Ordered-purchase.Received).ToString()));if(f==null)return;await Task.Run(()=>pos.ReceivePurchase(Session,purchase.Id,int.Parse(f["qty"])));break;
   case "sale.items":if(selected is not SaleRow sale)throw new DomainException("Select a sale.");var items=await Task.Run(()=>pos.SaleItems(Session,sale.Id));shownSaleId=sale.Id;Rows=items.Select(x=>new ItemRow(x.Id,x.ProductName,x.Quantity,Money.Amount(x.UnitPriceCents),Money.Amount(x.DiscountCents),Money.Amount(x.TaxCents),Money.Amount(x.TotalCents))).ToList();SelectedRow=null;Actions.Clear();AddAction("refresh","Refresh");AddAllowed("refund","Refund selected item","Sales.Refund");AddAction("sale.print","Print");return;
   case "refund":if(selected is not ItemRow item)throw new DomainException("Select an invoice item.");f=dialogs.Form("Refund / استرجاع",new Field("qty","Return quantity / الكمية المسترجعة","1"),new Field("restock","Restock sellable items? / إعادة للمخزون؟","true",Check:true),new Field("reason","Reason / السبب"));if(f==null)return;var refund=new RefundInput(Guid.NewGuid(),item.Id,int.Parse(f["qty"]),f["restock"]=="true",f["reason"]);await Task.Run(()=>pos.Refund(Session,refund));break;
   case "sale.print":var saleId=shownSaleId??(selected as SaleRow)?.Id??throw new DomainException("Select a sale.");var receipt=await Task.Run(()=>pos.Receipt(Session,saleId));printing.Receipt(receipt,settings);return;
   case "expense.add":f=dialogs.Form("Expense / مصروف",new Field("category","Category / البند"),new Field("description","Description / الوصف"),new Field("amount","Amount / المبلغ"));if(f==null)return;await Task.Run(()=>pos.AddExpense(Session,f["category"],f["description"],D(f["amount"])));break;
   case "shift.open":f=dialogs.Form("Open shift / فتح وردية",new Field("opening","Opening cash / رصيد البداية","0"));if(f==null)return;await Task.Run(()=>pos.OpenShift(Session,D(f["opening"])));break;
   case "shift.close":var expected=await Task.Run(()=>pos.ExpectedCash(Session));f=dialogs.Form($"Expected / المتوقع: {Money.Text(expected)}",new Field("counted","Counted cash / النقد الفعلي"),new Field("notes","Notes / ملاحظات"));if(f==null)return;var difference=await Task.Run(()=>pos.CloseShift(Session,D(f["counted"]),f["notes"]));Status="Cash difference / فرق النقد: "+Money.Text(difference);await Load();return;
   case "shift.cash":f=dialogs.Form("Cash in / out / حركة نقدية",new Field("amount","Positive deposit; negative withdrawal / موجب إيداع، سالب سحب"),new Field("reason","Reason / السبب"));if(f==null)return;await Task.Run(()=>pos.CashInOut(Session,D(f["amount"]),f["reason"]));break;
   case "shift.print":printing.Table(L["Shifts"],Rows.Cast<object>().ToList());return;
   case "user.add":f=dialogs.Form("Create user / إنشاء مستخدم",new Field("username","Username / اسم المستخدم"),new Field("name","Full name / الاسم الكامل"),new Field("password","Password (10+ characters, letter and digit) / كلمة المرور",Secret:true),new Field("role","Role / الدور",Choices:["Employee","Manager"]));if(f==null)return;await Task.Run(()=>security.CreateUser(Session,f["username"],f["name"],f["password"],f["role"]=="Manager"));f["password"]="";break;
   case "user.active":if(selected is not UserView user)throw new DomainException("Select a user.");await Task.Run(()=>security.SetActive(Session,user.Id,!user.IsActive));break;
   case "user.reset":if(selected is not UserView reset)throw new DomainException("Select a user.");f=dialogs.Form("Reset password / تعيين كلمة المرور",new Field("password","New password / كلمة المرور الجديدة",Secret:true));if(f==null)return;await Task.Run(()=>security.ResetPassword(Session,reset.Id,f["password"]));f["password"]="";break;
   case "user.permissions":if(selected is not UserView employee||employee.Role!="Employee")throw new DomainException("Select an Employee.");var perms=await Task.Run(()=>security.GetPermissions(Session,employee.Id));f=dialogs.Form("Employee permissions / صلاحيات الموظف",perms.Where(x=>!Permissions.ManagerOnly.Contains(x.Key)).Select(x=>new Field(x.Key,x.Key,x.Value?"true":"false",Check:true)).ToArray());if(f==null)return;foreach(var v in f)if((v.Value=="true")!=perms[v.Key])await Task.Run(()=>security.Override(Session,employee.Id,v.Key,v.Value=="true"));break;
   case "excel.template":var template=dialogs.Save("Excel (*.xlsx)|*.xlsx","ProductImportTemplate.xlsx");if(template!=null)await Task.Run(()=>excel.Template(Session,template));return;
   case "excel.import":var path=dialogs.Open("Excel (*.xlsx)|*.xlsx");if(path==null)return;var sheets=await Task.Run(()=>excel.Worksheets(Session,path));f=dialogs.Form("Import options / خيارات الاستيراد",new Field("sheet","Worksheet / الورقة",Choices:sheets.ToArray()),new Field("duplicates","Existing SKU / المنتج الموجود",Choices:["skip","update"]));if(f==null)return;var sheet=f["sheet"];var mode=f["duplicates"];var headers=await Task.Run(()=>excel.HeadersIn(Session,path,sheet));var mappingFields=new[]{"SKU","Barcode","ProductName","CostPrice","SellingPrice","Quantity","MinimumStock"}.Select(x=>new Field(x,x+(x is "SKU" or "ProductName" or "SellingPrice"?" (required / مطلوب)":" (optional / اختياري)"),headers.Contains(x)?x:"(omit)",Choices:new[]{"(omit)"}.Concat(headers).ToArray())).ToArray();var mapping=dialogs.Form("Map Excel columns / ربط أعمدة Excel",mappingFields);if(mapping==null)return;foreach(var h in mapping.Keys.ToList())if(mapping[h]=="(omit)")mapping[h]="";var importRows=await Task.Run(()=>excel.Read(Session,path,sheet,mapping));printing.PreviewRows("Import preview — Quantity ADDS stock / الكمية تضاف للمخزون",importRows.Cast<object>().ToList());if(!dialogs.Confirm($"Import {importRows.Count} rows? Quantity is ADDITIVE, never a replacement. Update mode changes prices. / الكمية تضاف للمخزون، وضع update يغيّر الأسعار."))return;var result=await Task.Run(()=>pos.Import(Session,importRows,mode));if(result.Errors.Count>0){var errorFile=dialogs.Save("Text (*.txt)|*.txt","ImportErrors.txt");if(errorFile!=null)await File.WriteAllLinesAsync(errorFile,result.Errors);throw new DomainException(string.Join("\n",result.Errors.Take(8)));}Status=$"Created={result.Created}; updated={result.Updated}; skipped={result.Skipped}";return;
   case "excel.export":var export=dialogs.Save("Excel (*.xlsx)|*.xlsx","Inventory.xlsx");if(export!=null)await Task.Run(()=>excel.ExportProducts(Session,export));return;
   case "report.export":if(currentReport==null)return;var reportPath=dialogs.Save("Excel (*.xlsx)|*.xlsx","Sales.xlsx");if(reportPath!=null)await Task.Run(()=>excel.ExportSales(Session,currentReport,reportPath));return;
   case "report.print":printing.Table(L["Reports"],Stats.Cast<object>().Concat(Rows.Cast<object>()).ToList());return;
   case "backup.create":var destination=dialogs.Save("SQLite backup (*.db)|*.db",$"POS-{DateTime.Now:yyyyMMdd-HHmmss}.db");if(destination==null)return;await Task.Run(()=>backup.Create(Session,destination));break;
   case "backup.restore":var restore=dialogs.Open("SQLite backup (*.db)|*.db");if(restore==null||!dialogs.Confirm("Restore replaces current data and signs you out. A safety backup will be created. / استبدال البيانات والخروج مع عمل نسخة أمان؟"))return;await Task.Run(()=>backup.Restore(Session,restore));EndSession?.Invoke();return;
   case "setting.save":if(selected is not SettingRow setting)throw new DomainException("Select a setting.");f=dialogs.Form(setting.Key,new Field("value","Value / القيمة",setting.Value));if(f==null)return;await Task.Run(()=>pos.SetSetting(Session,setting.Key,f["value"]));var currentKey=SelectedNav?.Key;LoadPreferences();SelectedNav=Navigation.Single(x=>x.Key==currentKey);return;
   default:throw new DomainException("Unknown action.");
  }
  await Load();Status="Saved successfully / تم الحفظ";
 });
 private Dictionary<string,string>? ContactForm(string title,string? name,string? phone,string? notes)=>dialogs.Form(title,new Field("name","Name / الاسم",name??""),new Field("phone","Phone / الهاتف",phone??""),new Field("notes","Notes / الملاحظات",notes??""));
 private static decimal D(string s){if(decimal.TryParse(s,NumberStyles.Number,CultureInfo.CurrentCulture,out var d)||decimal.TryParse(s,NumberStyles.Number,CultureInfo.InvariantCulture,out d))return d;throw new DomainException("Enter a valid numeric amount.");}
 private static long ChoiceId(string text)=>long.Parse(text.Split('|')[0].Trim());
 public async Task TryAutoBackup(){if(Busy||!int.TryParse(settings.GetValueOrDefault("AutoBackupMinutes","0"),out var interval)||interval<=0||DateTime.UtcNow-lastBackupAttempt<TimeSpan.FromMinutes(interval))return;lastBackupAttempt=DateTime.UtcNow;await Run(async()=>{if(!Can("Backup.Create"))return;var folder=settings.GetValueOrDefault("BackupDirectory",System.IO.Path.Combine(App.DataDirectory,"Backups"));if(string.IsNullOrWhiteSpace(folder))throw new DomainException("Set a backup directory first.");await Task.Run(()=>backup.Create(Session,System.IO.Path.Combine(folder,$"auto-{DateTime.UtcNow:yyyyMMdd-HHmmss}-{Guid.NewGuid():N}.db")));Status="Automatic backup saved / تم حفظ النسخة التلقائية";});}
 [RelayCommand] private void Logout(){if(Cart.Count>0&&!dialogs.Confirm("The unsuspended cart will be discarded. Sign out? / الخروج ومسح السلة غير المعلقة؟"))return;EndSession?.Invoke();}
 [RelayCommand] private void Lock()=>LockRequested?.Invoke();public event Action? LockRequested;
 public int AutoLockMinutes=>int.TryParse(settings.GetValueOrDefault("AutoLockMinutes"),out var n)?n:10;
 public bool Unlock(Window owner){var login=new LoginViewModel(security,false,Session.Username);var win=new LoginWindow(login){Owner=owner};if(win.ShowDialog()!=true||login.Authenticated==null)return false;Session=login.Authenticated;LoadPreferences();OnPropertyChanged(nameof(UserLabel));return true;}
 [RelayCommand] private Task ChangePasswordAsync()=>Run(async()=>{var f=dialogs.Form("Change password / تغيير كلمة المرور",new Field("old","Current password / كلمة المرور الحالية",Secret:true),new Field("new","New password / الجديدة",Secret:true));if(f==null)return;await Task.Run(()=>security.ChangePassword(Session,f["old"],f["new"]));f["old"]=f["new"]="";EndSession?.Invoke();});
}
