using CashierPOS.Core;
using System.Globalization;
using System.Text.Json;
namespace CashierPOS.Application;
public sealed class PosService(IDbFactory factory,SecurityService security,IClock clock) {
 private T Write<T>(Session s,Func<IPosDb,T> action){using var db=factory.Open();using var tx=db.Begin();security.ValidateSession(db,s);var value=action(db);db.Save();tx.Commit();return value;}
 public List<ProductView> Products(Session s,string search="",bool includeArchived=false){using var db=factory.Open();security.Require(db,s,"Products.View");var showCost=security.Can(db,s,"Products.Cost");return db.Set<Product>().Where(p=>includeArchived||p.IsActive).AsEnumerable().Where(p=>string.IsNullOrWhiteSpace(search)||$"{p.Name} {p.SKU} {p.Barcode}".Contains(search,StringComparison.OrdinalIgnoreCase)).OrderBy(p=>p.Name).Take(1000).Select(p=>new ProductView(p.Id,p.SKU,p.Barcode,p.Name,p.PriceCents,showCost?p.CostCents:null,p.Stock,p.MinimumStock,p.IsActive)).ToList();}
 public long SaveProduct(Session s,ProductInput input)=>Write(s,db=>{
  security.Require(db,s,input.Id==0?"Products.Create":"Products.Edit");ValidateProduct(input);
  var sku=SecurityService.Normalize(input.SKU);var barcode=input.Barcode.Trim();if(db.Set<Product>().Any(p=>p.Id!=input.Id&&(p.SKU==sku||(barcode!=""&&p.Barcode==barcode))))throw new DomainException("Duplicate SKU or barcode.");
  var p=input.Id==0?new Product():db.Set<Product>().Single(x=>x.Id==input.Id);
  if(input.Id!=0&&p.PriceCents!=Money.Cents(input.Price))security.Require(db,s,"Products.ChangePrice");
  var requestedCost=input.Id!=0&&!security.Can(db,s,"Products.Cost")&&input.Cost==0?p.CostCents:Money.Cents(input.Cost);
  if((input.Id==0&&input.Cost!=0)||(input.Id!=0&&p.CostCents!=requestedCost))security.Require(db,s,"Products.Cost");
  var old=$"{p.Name}; price={p.PriceCents}; cost={p.CostCents}";
  p.SKU=sku;p.Barcode=barcode;p.Name=input.Name.Trim();p.CostCents=requestedCost;p.PriceCents=Money.Cents(input.Price);p.MinimumStock=input.MinimumStock;p.CategoryId=input.CategoryId;p.SupplierId=input.SupplierId;p.Version++;
  if(input.Id==0)db.Add(p);db.Save();security.Log(db,s.UserId,"Product.Save","Product",p.Id,old+$" => {p.Name}; price={p.PriceCents}; cost={p.CostCents}");return p.Id;
 });
 public void ArchiveProduct(Session s,long id)=>Write(s,db=>{security.Require(db,s,"Products.Archive");var p=db.Set<Product>().Single(x=>x.Id==id);p.IsActive=false;p.Version++;security.Log(db,s.UserId,"Product.Archive","Product",id);return true;});
 public void AdjustStock(Session s,long id,int delta,string reason,Guid? approval=null)=>Write(s,db=>{if(string.IsNullOrWhiteSpace(reason)||delta==0)throw new DomainException("A nonzero quantity and reason are required.");var approver=security.RequireOrApproval(db,s,"Inventory.Adjust",$"{id}|{delta}|{reason}",approval);Move(db,s,id,delta,"Adjustment",null,reason,approver);security.Log(db,s.UserId,"Inventory.Adjust","Product",id,$"Quantity change={delta}; reason={reason}",approver);return true;});
 internal void Move(IPosDb db,Session s,long productId,int delta,string reference,long? id,string reason,long? approvedBy=null){var p=db.Set<Product>().Single(x=>x.Id==productId);var after=checked(p.Stock+delta);if(after<0)throw new DomainException("Insufficient stock: "+p.Name);db.Add(new InventoryMovement{ProductId=p.Id,Type=reference,QuantityChange=delta,BeforeQuantity=p.Stock,AfterQuantity=after,ReferenceType=reference,ReferenceId=id,UserId=s.UserId,ApprovedBy=approvedBy,Reason=reason,CreatedAtUtc=clock.UtcNow});p.Stock=after;p.Version++;}
 public List<InventoryMovement> Movements(Session s){using var db=factory.Open();security.Require(db,s,"Inventory.View");return db.Set<InventoryMovement>().OrderByDescending(m=>m.Id).Take(500).ToList();}
 public long OpenShift(Session s,decimal opening)=>Write(s,db=>{security.Require(db,s,"Shifts.Own");if(opening<0)throw new DomainException("Opening cash cannot be negative.");if(db.Set<CashierShift>().Any(x=>x.ClosedAtUtc==null))throw new DomainException("A shift is already open on this cash drawer. Close it first.");var shift=new CashierShift{UserId=s.UserId,OpeningCents=Money.Cents(opening),OpenedAtUtc=clock.UtcNow};db.Add(shift);db.Save();security.Log(db,s.UserId,"Shift.Open","Shift",shift.Id);return shift.Id;});
 private CashierShift ActiveShift(IPosDb db,Session s)=>db.Set<CashierShift>().SingleOrDefault(x=>x.UserId==s.UserId&&x.ClosedAtUtc==null)??throw new DomainException("Open your own cashier shift before processing payments.");
 public List<CashierShift> Shifts(Session s){using var db=factory.Open();security.Require(db,s,"Shifts.Own");var all=security.Can(db,s,"Shifts.All");return db.Set<CashierShift>().Where(x=>all||x.UserId==s.UserId).OrderByDescending(x=>x.Id).Take(500).ToList();}
 private long Expected(IPosDb db,CashierShift shift){var sales=db.Set<Sale>().Where(x=>x.ShiftId==shift.Id).Select(x=>x.Id).ToArray();var refunds=db.Set<Refund>().Where(x=>x.ShiftId==shift.Id).Select(x=>x.Id).ToArray();return checked(shift.OpeningCents+db.Set<Payment>().Where(x=>sales.Contains(x.SaleId)&&x.Method=="Cash").AsEnumerable().Sum(x=>x.AmountCents)-db.Set<RefundPayment>().Where(x=>refunds.Contains(x.RefundId)&&x.Method=="Cash").AsEnumerable().Sum(x=>x.AmountCents)+db.Set<CashMovement>().Where(x=>x.ShiftId==shift.Id).AsEnumerable().Sum(x=>x.AmountCents));}
 public long ExpectedCash(Session s){using var db=factory.Open();security.Require(db,s,"Shifts.Own");return Expected(db,ActiveShift(db,s));}
 public void CashInOut(Session s,decimal amount,string reason)=>Write(s,db=>{security.Require(db,s,"Shifts.Own");if(amount==0||string.IsNullOrWhiteSpace(reason))throw new DomainException("Amount and reason are required.");var shift=ActiveShift(db,s);var cents=Money.Cents(amount);if(Expected(db,shift)+cents<0)throw new DomainException("Cash out exceeds expected drawer cash.");db.Add(new CashMovement{ShiftId=shift.Id,AmountCents=cents,Reason=reason,UserId=s.UserId,CreatedAtUtc=clock.UtcNow});security.Log(db,s.UserId,"Shift.CashMovement","Shift",shift.Id,$"{cents}; {reason}");return true;});
 public long CloseShift(Session s,decimal counted,string notes)=>Write(s,db=>{security.Require(db,s,"Shifts.Own");if(counted<0)throw new DomainException("Counted cash cannot be negative.");var shift=ActiveShift(db,s);shift.ExpectedCents=Expected(db,shift);shift.CountedCents=Money.Cents(counted);shift.Notes=notes;shift.ClosedAtUtc=clock.UtcNow;security.Log(db,s.UserId,"Shift.Close","Shift",shift.Id,$"Expected={shift.ExpectedCents}; counted={shift.CountedCents}");return shift.CountedCents.Value-shift.ExpectedCents.Value;});
 public SaleReceipt Checkout(Session s,Checkout input)=>Write(s,db=>{
  security.Require(db,s,"Sales.Create");if(input.RequestId==Guid.Empty)throw new DomainException("Missing checkout request id.");
  var existing=db.Set<Sale>().SingleOrDefault(x=>x.RequestId==input.RequestId);if(existing!=null){if(existing.UserId!=s.UserId)throw new DomainException("Request id belongs to another user.");if(existing.RequestHash!=SecurityService.Hash(JsonSerializer.Serialize(input with{Approval=null})))throw new DomainException("This checkout id was already used for different data.");return SafeReceipt(db,s,existing);}
  var shift=ActiveShift(db,s);if(input.Lines.Count==0||input.Lines.Count>200||input.Lines.Any(x=>x.Quantity<=0)||input.Lines.Select(x=>x.ProductId).Distinct().Count()!=input.Lines.Count)throw new DomainException("Cart must contain unique products and positive whole quantities.");
  if(input.CustomerId!=null&&!db.Set<Customer>().Any(x=>x.Id==input.CustomerId))throw new DomainException("Customer does not exist.");
  var lines=new List<SaleItem>();bool hasOverride=false;
  foreach(var c in input.Lines){var p=db.Set<Product>().Single(x=>x.Id==c.ProductId);if(!p.IsActive||p.Stock<c.Quantity)throw new DomainException("Product is unavailable or stock is insufficient: "+p.Name);if(c.OverridePriceCents==null&&c.ExpectedPriceCents!=null&&c.ExpectedPriceCents!=p.PriceCents)throw new DomainException("Product price changed. Refresh the cart before checkout: "+p.Name);var price=c.OverridePriceCents??p.PriceCents;if(price<0)throw new DomainException("Negative prices are invalid.");hasOverride|=price!=p.PriceCents;lines.Add(new SaleItem{ProductId=p.Id,ProductName=p.Name,SKU=p.SKU,Quantity=c.Quantity,UnitPriceCents=price,CostCents=checked(p.CostCents*c.Quantity)});}
  var subtotal=lines.Sum(l=>checked(l.UnitPriceCents*l.Quantity));if(subtotal<=0||input.DiscountCents<0||input.DiscountCents>subtotal)throw new DomainException("Invalid sale total or discount.");
  var payload=JsonSerializer.Serialize(input with{Approval=null});long? approver=null;
  var needsPrice=hasOverride&&!security.Can(db,s,"Sales.OverridePrice");var maxPct=SettingDecimal(db,"EmployeeDiscountPercent",0);
  var needsDiscount=input.DiscountCents>0&&(!security.Can(db,s,"Sales.ApplyDiscount")||(!security.IsManager(db,s)&&input.DiscountCents*100m/subtotal>maxPct));
  if(needsPrice||needsDiscount)approver=security.RequireOrApproval(db,s,needsPrice?"Sales.OverridePrice":"Sales.ApplyDiscount",payload,input.Approval,true);
  var inclusive=Setting(db,"TaxInclusive","false")=="true";var taxRate=SettingDecimal(db,"TaxPercent",0);var totals=Calculate(lines,input.DiscountCents,taxRate,inclusive);
  if(input.Payments.Count==0||input.Payments.Any(p=>p.AmountCents<0||p.Method is not("Cash" or "Card"))||input.Payments.Select(p=>p.Method).Distinct().Count()!=input.Payments.Count)throw new DomainException("Use one nonnegative tender per Cash / Card method.");
  var tender=input.Payments.Sum(p=>p.AmountCents);if(tender<totals.Total)throw new DomainException("Payment is insufficient.");var change=tender-totals.Total;var cash=input.Payments.SingleOrDefault(p=>p.Method=="Cash")?.AmountCents??0;if(change>cash)throw new DomainException("Only cash may produce change; reduce the card amount.");
  var sale=new Sale{RequestId=input.RequestId,RequestHash=SecurityService.Hash(JsonSerializer.Serialize(input with{Approval=null})),UserId=s.UserId,ShiftId=shift.Id,CustomerId=input.CustomerId,SubtotalCents=subtotal,DiscountCents=input.DiscountCents,TaxCents=totals.Tax,TotalCents=totals.Total,CostCents=lines.Sum(x=>x.CostCents),ChangeCents=change,Notes=input.Notes,CreatedAtUtc=clock.UtcNow,InvoiceNumber="PENDING-"+input.RequestId.ToString("N")};db.Add(sale);db.Save();sale.InvoiceNumber=$"POS-{sale.Id:D8}";
  foreach(var l in lines){l.SaleId=sale.Id;db.Add(l);Move(db,s,l.ProductId,-l.Quantity,"Sale",sale.Id,"Checkout",approver);}
  foreach(var p in input.Payments){var applied=p.AmountCents-(p.Method=="Cash"?change:0);if(applied>0)db.Add(new Payment{SaleId=sale.Id,Method=p.Method,AmountCents=applied});}
  security.Log(db,s.UserId,"Sale.Complete","Sale",sale.Id,$"Total={sale.TotalCents}; discount={sale.DiscountCents}",approver);db.Save();return SafeReceipt(db,s,sale);
 });
 public static (long Tax,long Total) Calculate(List<SaleItem> lines,long discount,decimal taxPercent,bool inclusive){
  if(taxPercent<0||taxPercent>100)throw new DomainException("Tax rate must be 0–100.");
  var subtotal=lines.Sum(l=>checked(l.UnitPriceCents*l.Quantity));if(subtotal<=0||discount<0||discount>subtotal)throw new DomainException("Invalid discount.");
  var allocations=lines.Select(l=>(long)decimal.Floor(discount*(decimal)(l.UnitPriceCents*l.Quantity)/subtotal)).ToArray();var remainder=discount-allocations.Sum();for(var i=0;remainder>0;i++,remainder--)allocations[i%lines.Count]++;
  for(var i=0;i<lines.Count;i++){var l=lines[i];l.DiscountCents=allocations[i];var net=checked(l.UnitPriceCents*l.Quantity-l.DiscountCents);l.TaxCents=checked((long)decimal.Round(inclusive?net*taxPercent/(100m+taxPercent):net*taxPercent/100m,0,MidpointRounding.AwayFromZero));l.TotalCents=inclusive?net:checked(net+l.TaxCents);}
  return(lines.Sum(x=>x.TaxCents),lines.Sum(x=>x.TotalCents));
 }
 public SaleReceipt Receipt(Session s,long saleId){using var db=factory.Open();security.Require(db,s,"Receipts.Print");var sale=db.Set<Sale>().Single(x=>x.Id==saleId);if(sale.UserId!=s.UserId)security.Require(db,s,"Sales.ViewAll");else security.Require(db,s,"Sales.ViewOwn");return SafeReceipt(db,s,sale);}
 private SaleReceipt SafeReceipt(IPosDb db,Session s,Sale sale){var receipt=Receipt(db,sale);if(security.Can(db,s,"Products.Cost"))return receipt;var redacted=JsonSerializer.Deserialize<SaleReceipt>(JsonSerializer.Serialize(receipt))!;redacted.Sale.CostCents=0;foreach(var item in redacted.Items)item.CostCents=0;return redacted;}
 private SaleReceipt Receipt(IPosDb db,Sale sale)=>new(sale,db.Set<SaleItem>().Where(x=>x.SaleId==sale.Id).ToList(),db.Set<Payment>().Where(x=>x.SaleId==sale.Id).ToList(),db.Set<User>().Single(x=>x.Id==sale.UserId).FullName);
 public List<SaleItem> SaleItems(Session s,long saleId){using var db=factory.Open();var sale=db.Set<Sale>().Single(x=>x.Id==saleId);security.Require(db,s,sale.UserId==s.UserId?"Sales.ViewOwn":"Sales.ViewAll");return db.Set<SaleItem>().Where(x=>x.SaleId==saleId).Select(x=>new SaleItem{Id=x.Id,SaleId=x.SaleId,ProductId=x.ProductId,ProductName=x.ProductName,SKU=x.SKU,Quantity=x.Quantity,UnitPriceCents=x.UnitPriceCents,TotalCents=x.TotalCents,TaxCents=x.TaxCents,DiscountCents=x.DiscountCents}).ToList();}
 public long Refund(Session s,RefundInput input)=>Write(s,db=>{
  var existing=db.Set<Refund>().SingleOrDefault(x=>x.RequestId==input.RequestId);if(existing!=null){security.Require(db,s,"Sales.ViewOwn");if(existing.UserId!=s.UserId)throw new DomainException("Duplicate request belongs to another user.");if(existing.SaleItemId!=input.SaleItemId||existing.Quantity!=input.Quantity||existing.Restock!=input.Restock||existing.Reason!=input.Reason)throw new DomainException("Refund id was already used for different data.");return existing.Id;}
  if(input.RequestId==Guid.Empty||input.Quantity<=0||string.IsNullOrWhiteSpace(input.Reason))throw new DomainException("Valid request, positive quantity and refund reason are required.");
  var approver=security.RequireOrApproval(db,s,"Sales.Refund",JsonSerializer.Serialize(input with{Approval=null}),input.Approval);var shift=ActiveShift(db,s);
  var item=db.Set<SaleItem>().Single(x=>x.Id==input.SaleItemId);var sale=db.Set<Sale>().Single(x=>x.Id==item.SaleId);var old=db.Set<Refund>().Where(x=>x.SaleItemId==item.Id).ToList();var returned=old.Sum(x=>x.Quantity);if(returned+input.Quantity>item.Quantity)throw new DomainException("Refund quantity exceeds the remaining quantity sold.");
  long Portion(long original,long prior)=>checked((long)decimal.Round(original*(decimal)(returned+input.Quantity)/item.Quantity,0,MidpointRounding.AwayFromZero))-prior;
  var r=new Refund{RequestId=input.RequestId,SaleId=sale.Id,SaleItemId=item.Id,UserId=s.UserId,ShiftId=shift.Id,Quantity=input.Quantity,AmountCents=Portion(item.TotalCents,old.Sum(x=>x.AmountCents)),TaxCents=Portion(item.TaxCents,old.Sum(x=>x.TaxCents)),CostCents=Portion(item.CostCents,old.Sum(x=>x.CostCents)),Reason=input.Reason,Restock=input.Restock,CreatedAtUtc=clock.UtcNow};db.Add(r);db.Save();
  var remaining=r.AmountCents;foreach(var p in db.Set<Payment>().Where(x=>x.SaleId==sale.Id).OrderBy(x=>x.Id).ToList()){var paidBack=db.Set<RefundPayment>().Where(x=>x.PaymentId==p.Id).AsEnumerable().Sum(x=>x.AmountCents);var amount=Math.Min(remaining,p.AmountCents-paidBack);if(amount>0){db.Add(new RefundPayment{RefundId=r.Id,PaymentId=p.Id,Method=p.Method,AmountCents=amount});remaining-=amount;}}if(remaining!=0)throw new DomainException("Refund exceeds original payment capacity.");
  if(input.Restock){var product=db.Set<Product>().Single(x=>x.Id==item.ProductId);product.CostCents=checked((long)decimal.Round((product.CostCents*(decimal)product.Stock+r.CostCents)/(product.Stock+input.Quantity),0,MidpointRounding.AwayFromZero));Move(db,s,item.ProductId,input.Quantity,"Refund",r.Id,input.Reason,approver);}
  security.Log(db,s.UserId,"Sale.Refund","Refund",r.Id,$"Sale={sale.Id}; qty={r.Quantity}; amount={r.AmountCents}; reason={input.Reason}",approver);return r.Id;
 });
 public Report Report(Session s,DateTime fromUtc,DateTime toUtc){using var db=factory.Open();security.Require(db,s,"Reports.ViewOwn");if(toUtc<=fromUtc)throw new DomainException("End date must follow start date.");var all=security.Can(db,s,"Reports.ViewAll");var sales=db.Set<Sale>().Where(x=>x.CreatedAtUtc>=fromUtc&&x.CreatedAtUtc<toUtc&&(all||x.UserId==s.UserId)).ToList();var refunds=db.Set<Refund>().Where(x=>x.CreatedAtUtc>=fromUtc&&x.CreatedAtUtc<toUtc&&(all||x.UserId==s.UserId)).ToList();var tax=sales.Sum(x=>x.TaxCents)-refunds.Sum(x=>x.TaxCents);var revenue=sales.Sum(x=>x.TotalCents)-refunds.Sum(x=>x.AmountCents)-tax;var costs=sales.Sum(x=>x.CostCents)-refunds.Where(x=>x.Restock).Sum(x=>x.CostCents);var expenses=all?db.Set<Expense>().Where(x=>x.CreatedAtUtc>=fromUtc&&x.CreatedAtUtc<toUtc).AsEnumerable().Sum(x=>x.AmountCents):0;var sensitive=all&&security.Can(db,s,"Products.Cost");var redacted=sales.Select(x=>new Sale{Id=x.Id,InvoiceNumber=x.InvoiceNumber,UserId=x.UserId,CreatedAtUtc=x.CreatedAtUtc,TotalCents=x.TotalCents,DiscountCents=x.DiscountCents,TaxCents=x.TaxCents,CostCents=sensitive?x.CostCents:0}).ToList();return new Report(fromUtc,toUtc,sales.Sum(x=>x.TotalCents),refunds.Sum(x=>x.AmountCents),revenue,tax,sensitive?revenue-costs:null,sensitive?expenses:null,sensitive?revenue-costs-expenses:null,sales.Count,db.Set<Product>().Count(p=>p.IsActive&&p.Stock<=p.MinimumStock),redacted);}
 public long SaveCustomer(Session s,long id,string name,string phone,string notes)=>Write(s,db=>{security.Require(db,s,id==0?"Customers.Create":"Customers.Edit");if(string.IsNullOrWhiteSpace(name))throw new DomainException("Customer name is required.");var c=id==0?new Customer():db.Set<Customer>().Single(x=>x.Id==id);c.Name=name.Trim();c.Phone=phone;c.Notes=notes;if(id==0)db.Add(c);db.Save();security.Log(db,s.UserId,"Customer.Save","Customer",c.Id);return c.Id;});
 public List<Customer> Customers(Session s){using var db=factory.Open();security.Require(db,s,"Customers.View");return db.Set<Customer>().OrderBy(x=>x.Name).Take(1000).ToList();}
 public long SaveSupplier(Session s,long id,string name,string phone,string notes)=>Write(s,db=>{security.Require(db,s,"Suppliers.Manage");if(string.IsNullOrWhiteSpace(name))throw new DomainException("Supplier name is required.");var v=id==0?new Supplier():db.Set<Supplier>().Single(x=>x.Id==id);v.Name=name.Trim();v.Phone=phone;v.Notes=notes;if(id==0)db.Add(v);db.Save();security.Log(db,s.UserId,"Supplier.Save","Supplier",v.Id);return v.Id;});
 public List<Supplier> Suppliers(Session s){using var db=factory.Open();security.Require(db,s,"Suppliers.Manage");return db.Set<Supplier>().OrderBy(x=>x.Name).ToList();}
 public List<Category> Categories(Session s){using var db=factory.Open();security.Require(db,s,"Products.View");return db.Set<Category>().OrderBy(x=>x.Name).ToList();}
 public long AddCategory(Session s,string name)=>Write(s,db=>{security.Require(db,s,"Products.Edit");if(string.IsNullOrWhiteSpace(name)||db.Set<Category>().Any(x=>x.Name==name.Trim()))throw new DomainException("Category name is required and must be unique.");var c=new Category{Name=name.Trim()};db.Add(c);db.Save();return c.Id;});
 public long CreatePurchase(Session s,long supplierId,string invoice,List<PurchaseLine> lines)=>Write(s,db=>{security.Require(db,s,"Purchases.Manage");if(!db.Set<Supplier>().Any(x=>x.Id==supplierId)||lines.Count==0||lines.Any(x=>x.Quantity<=0||x.CostCents<0)||lines.Select(x=>x.ProductId).Distinct().Count()!=lines.Count)throw new DomainException("Valid supplier and unique positive purchase lines are required.");var p=new Purchase{SupplierId=supplierId,UserId=s.UserId,SupplierInvoice=invoice,TotalCents=lines.Sum(x=>checked(x.CostCents*x.Quantity)),CreatedAtUtc=clock.UtcNow};db.Add(p);db.Save();foreach(var l in lines)db.Add(new PurchaseItem{PurchaseId=p.Id,ProductId=l.ProductId,Ordered=l.Quantity,UnitCostCents=l.CostCents});security.Log(db,s.UserId,"Purchase.Create","Purchase",p.Id);return p.Id;});
 public List<PurchaseItem> PurchaseItems(Session s){using var db=factory.Open();security.Require(db,s,"Purchases.Manage");return db.Set<PurchaseItem>().OrderByDescending(x=>x.Id).Take(500).ToList();}
 public void ReceivePurchase(Session s,long itemId,int quantity)=>Write(s,db=>{security.Require(db,s,"Purchases.Manage");var item=db.Set<PurchaseItem>().Single(x=>x.Id==itemId);if(quantity<=0||quantity>item.Ordered-item.Received)throw new DomainException("Receiving exceeds remaining order quantity.");var p=db.Set<Product>().Single(x=>x.Id==item.ProductId);p.CostCents=checked((long)decimal.Round((p.CostCents*(decimal)p.Stock+item.UnitCostCents*(decimal)quantity)/(p.Stock+quantity),0,MidpointRounding.AwayFromZero));Move(db,s,p.Id,quantity,"Purchase",item.PurchaseId,"Stock received");item.Received+=quantity;security.Log(db,s.UserId,"Purchase.Receive","PurchaseItem",item.Id,"Quantity="+quantity);return true;});
 public long AddExpense(Session s,string category,string description,decimal amount)=>Write(s,db=>{security.Require(db,s,"Expenses.Create");if(amount<=0||string.IsNullOrWhiteSpace(category)||string.IsNullOrWhiteSpace(description))throw new DomainException("Positive amount, category and description are required.");var e=new Expense{Category=category,Description=description,AmountCents=Money.Cents(amount),UserId=s.UserId,CreatedAtUtc=clock.UtcNow};db.Add(e);db.Save();security.Log(db,s.UserId,"Expense.Create","Expense",e.Id);return e.Id;});
 public List<Expense> Expenses(Session s){using var db=factory.Open();security.Require(db,s,"Expenses.View");return db.Set<Expense>().OrderByDescending(x=>x.Id).Take(500).ToList();}
 public List<AuditLog> Audit(Session s){using var db=factory.Open();security.Require(db,s,"AuditLogs.View");return db.Set<AuditLog>().OrderByDescending(x=>x.Id).Take(1000).ToList();}
 public long Suspend(Session s,string name,List<CartLine> lines)=>Write(s,db=>{security.Require(db,s,"Sales.Suspend");if(lines.Count==0)throw new DomainException("Cart is empty.");var x=new SuspendedSale{UserId=s.UserId,Name=name,CartJson=JsonSerializer.Serialize(lines),CreatedAtUtc=clock.UtcNow};db.Add(x);db.Save();return x.Id;});
 public List<SuspendedSale> Suspended(Session s){using var db=factory.Open();security.Require(db,s,"Sales.Suspend");return db.Set<SuspendedSale>().Where(x=>x.UserId==s.UserId).OrderByDescending(x=>x.Id).ToList();}
 public List<CartLine> Resume(Session s,long id)=>Write(s,db=>{security.Require(db,s,"Sales.Suspend");var x=db.Set<SuspendedSale>().Single(x=>x.Id==id&&x.UserId==s.UserId);var cart=JsonSerializer.Deserialize<List<CartLine>>(x.CartJson)??[];db.Remove(x);return cart;});
 public Dictionary<string,string> Settings(Session s){using var db=factory.Open();security.ValidateSession(db,s);return db.Set<ApplicationSetting>().ToDictionary(x=>x.Key,x=>x.Value);}
 public void SetSetting(Session s,string key,string value)=>Write(s,db=>{security.Require(db,s,"Settings.Manage");if(!new[]{"StoreName","StoreAddress","StorePhone","Currency","Language","Theme","TaxPercent","TaxInclusive","EmployeeDiscountPercent","AutoLockMinutes","ReceiptFooter","AutoBackupMinutes","BackupDirectory"}.Contains(key))throw new DomainException("Unknown setting.");if(key is "TaxPercent" or "EmployeeDiscountPercent" or "AutoLockMinutes" or "AutoBackupMinutes"){if(!decimal.TryParse(value,NumberStyles.Number,CultureInfo.InvariantCulture,out var d)||d<0||d>(key=="AutoBackupMinutes"?1440:100)||key=="AutoLockMinutes"&&d<1)throw new DomainException("Invalid numeric setting.");}if(key=="Language"&&value is not("ar" or "en")||key=="Theme"&&value is not("dark" or "light")||key=="TaxInclusive"&&value is not("true" or "false"))throw new DomainException("Invalid setting value.");var v=db.Set<ApplicationSetting>().SingleOrDefault(x=>x.Key==key);if(v==null)db.Add(new ApplicationSetting{Key=key,Value=value});else v.Value=value;security.Log(db,s.UserId,"Setting.Change","Setting",v?.Id,$"{key}={value}");return true;});
 internal static string Setting(IPosDb db,string key,string fallback)=>db.Set<ApplicationSetting>().SingleOrDefault(x=>x.Key==key)?.Value??fallback;
 internal static decimal SettingDecimal(IPosDb db,string key,decimal fallback)=>decimal.TryParse(Setting(db,key,""),NumberStyles.Number,CultureInfo.InvariantCulture,out var d)?d:fallback;
 public ImportResult Import(Session s,List<ImportRow> rows,string duplicates)=>Write(s,db=>{
  security.Require(db,s,"Excel.Import");if(duplicates is not("skip" or "update"))throw new DomainException("Choose skip or update.");var errors=new List<string>();var seen=new HashSet<string>();var bars=new HashSet<string>();
  foreach(var r in rows){try{ValidateProduct(new ProductInput(0,r.SKU,r.Barcode,r.Name,r.Cost,r.Price,r.MinimumStock));if(r.Quantity<0)throw new DomainException("Quantity must be nonnegative.");if(!seen.Add(SecurityService.Normalize(r.SKU)))throw new DomainException("Duplicate SKU within file.");if(r.Barcode!=""&&!bars.Add(r.Barcode))throw new DomainException("Duplicate barcode within file.");var sku=SecurityService.Normalize(r.SKU);if(r.Barcode!=""&&db.Set<Product>().Any(p=>p.SKU!=sku&&p.Barcode==r.Barcode))throw new DomainException("Barcode belongs to another SKU.");}catch(DomainException e){errors.Add($"Row {r.Row}: {e.Message}");}}
  if(errors.Count>0)return new ImportResult(0,0,0,errors);int created=0,updated=0,skipped=0;
  foreach(var r in rows){var sku=SecurityService.Normalize(r.SKU);var p=db.Set<Product>().SingleOrDefault(x=>x.SKU==sku);if(p!=null&&duplicates=="skip"){skipped++;continue;}security.Require(db,s,p==null?"Products.Create":"Products.Edit");security.Require(db,s,"Products.Cost");security.Require(db,s,"Products.ChangePrice");security.Require(db,s,"Inventory.Adjust");if(p==null){p=new Product{SKU=sku};db.Add(p);created++;}else updated++;if(!p.IsActive)throw new DomainException("Cannot import into an archived product.");p.Barcode=r.Barcode;p.Name=r.Name;p.CostCents=Money.Cents(r.Cost);p.PriceCents=Money.Cents(r.Price);p.MinimumStock=r.MinimumStock;p.Version++;db.Save();if(r.Quantity>0)Move(db,s,p.Id,r.Quantity,"ExcelImport",null,"Explicit additive opening / receiving quantity");}
  security.Log(db,s.UserId,"Excel.Import","Product",null,$"Created={created}; updated={updated}; skipped={skipped}");return new ImportResult(created,updated,skipped,errors);
 });
 private static void ValidateProduct(ProductInput p){if(string.IsNullOrWhiteSpace(p.SKU)||p.SKU.Length>64||string.IsNullOrWhiteSpace(p.Name)||p.Name.Length>200||p.Barcode.Length>128||p.Cost<0||p.Price<0||p.MinimumStock<0||p.Cost!=decimal.Round(p.Cost,2)||p.Price!=decimal.Round(p.Price,2))throw new DomainException("Product needs SKU/name, nonnegative prices with at most two decimal places, and nonnegative minimum stock.");}
}
