
using CashierPOS.Application;
using CashierPOS.Core;
using CashierPOS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Xunit;
namespace CashierPOS.Tests;
public sealed class TestClock:IClock {public DateTime UtcNow{get;set;}=new(2026,10,8,10,0,0,DateTimeKind.Utc);}
public sealed class Fixture:IDisposable {
 public string Folder{get;}=Path.Combine(Path.GetTempPath(),"CashierPOS-tests-"+Guid.NewGuid());public SqliteFactory Factory{get;}public SecurityService Security{get;}public PosService Pos{get;}public Session Manager{get;}public TestClock Clock{get;}=new();
 public Fixture(){Directory.CreateDirectory(Folder);Factory=new SqliteFactory(Path.Combine(Folder,"pos.db"));Factory.Initialize();Security=new SecurityService(Factory,new PasswordHasher(),Clock);Pos=new PosService(Factory,Security,Clock);Manager=Security.Setup("manager","Store manager","SafePass1234");}
 public Session Employee(){Security.CreateUser(Manager,"employee","Cashier","Employee1234");return Security.Login("employee","Employee1234");}
 public long Product(decimal price=10m,decimal cost=4m,int stock=10){var id=Pos.SaveProduct(Manager,new ProductInput(0,"SKU-"+Guid.NewGuid().ToString("N"),"","Product",cost,price,2));if(stock>0)Pos.AdjustStock(Manager,id,stock,"Opening balance");return id;}
 public Checkout Input(long id,int quantity=1,long tender=1000)=>new(Guid.NewGuid(),[new CartLine(id,quantity)],0,[new Tender("Cash",tender)]);
 public void Dispose(){try{Directory.Delete(Folder,true);}catch(IOException){}}
}
public sealed class IntegrationTests {
 [Fact] public void FirstRunHasNoDefaultUserAndSetupCannotRunTwice(){using var f=new Fixture();Assert.False(f.Security.NeedsSetup());Assert.Throws<DomainException>(()=>f.Security.Setup("x","X","OtherPass1234"));using var db=f.Factory.Open();Assert.Single(db.Set<User>());Assert.DoesNotContain("SafePass",db.Set<User>().Single().PasswordHash);}
 [Fact] public void PasswordHashUsesFreshSaltAndRejectsBadPasswords(){var h=new PasswordHasher();var a=h.Hash("Password1234");var b=h.Hash("Password1234");Assert.NotEqual(a,b);Assert.True(h.Verify("Password1234",a));Assert.False(h.Verify("incorrect",a));Assert.False(h.Verify("Password1234","bad"));}
 [Fact] public void LockoutExpiresAndSuccessfulLoginClearsFailures(){using var f=new Fixture();for(int i=0;i<5;i++)Assert.Throws<DomainException>(()=>f.Security.Login("manager","wrong"));Assert.Throws<DomainException>(()=>f.Security.Login("manager","SafePass1234"));f.Clock.UtcNow=f.Clock.UtcNow.AddMinutes(6);Assert.True(f.Security.Login(" MANAGER ","SafePass1234").IsManager);using var db=f.Factory.Open();Assert.Equal(0,db.Set<User>().Single().FailedLoginAttempts);}
 [Fact] public void LastActiveManagerCannotBeDeactivated(){using var f=new Fixture();Assert.Throws<DomainException>(()=>f.Security.SetActive(f.Manager,f.Manager.UserId,false));}
 [Fact] public void DisabledUserAndResetPasswordRevokeOldSessions(){using var f=new Fixture();var e=f.Employee();f.Security.SetActive(f.Manager,e.UserId,false);Assert.Throws<DomainException>(()=>f.Pos.Products(e));Assert.Throws<DomainException>(()=>f.Security.Login("employee","Employee1234"));f.Security.SetActive(f.Manager,e.UserId,true);var fresh=f.Security.Login("employee","Employee1234");f.Security.ResetPassword(f.Manager,e.UserId,"NewSecret1234");Assert.Throws<DomainException>(()=>f.Pos.Products(fresh));Assert.NotNull(f.Security.Login("employee","NewSecret1234"));}
 [Fact] public void EmployeeCannotCallManagerServicesDirectlyOrForgeRole(){using var f=new Fixture();var e=f.Employee();Assert.Throws<DomainException>(()=>f.Security.CreateUser(e,"intruder","X","Password1234"));Assert.Throws<DomainException>(()=>f.Security.Override(e,e.UserId,"Users.Manage",true));Assert.Throws<DomainException>(()=>f.Security.Users(e with{IsManager=true}));Assert.Throws<DomainException>(()=>f.Security.Users(e with{UserId=f.Manager.UserId}));Assert.Throws<DomainException>(()=>f.Pos.SaveProduct(e,new ProductInput(0,"BAD","","Bad",1,2,0)));}
 [Fact] public void OverridesAreEffectiveImmediatelyAndManagerOnlyGrantsAreRejected(){using var f=new Fixture();var e=f.Employee();Assert.False(f.Security.Can(e,"Customers.Create"));f.Security.Override(f.Manager,e.UserId,"Customers.Create",true);Assert.True(f.Security.Can(e,"Customers.Create"));Assert.True(f.Pos.SaveCustomer(e,0,"Customer","","")>0);f.Security.Override(f.Manager,e.UserId,"Customers.Create",false);Assert.Throws<DomainException>(()=>f.Pos.SaveCustomer(e,0,"Customer","",""));f.Security.Override(f.Manager,e.UserId,"Customers.Create",null);Assert.False(f.Security.Can(e,"Customers.Create"));Assert.Throws<DomainException>(()=>f.Security.Override(f.Manager,e.UserId,"Backup.Restore",true));}
 [Fact] public void EmployeeProductAndReceiptProjectionsDoNotRevealCosts(){using var f=new Fixture();var e=f.Employee();var id=f.Product();Assert.Null(f.Pos.Products(e).Single().CostCents);f.Pos.OpenShift(e,0);var sale=f.Pos.Checkout(e,f.Input(id));Assert.Equal(0,sale.Sale.CostCents);Assert.Equal(0,sale.Items.Single().CostCents);Assert.Equal(0,f.Pos.Receipt(e,sale.Sale.Id).Sale.CostCents);Assert.Null(f.Pos.Report(e,f.Clock.UtcNow.Date,f.Clock.UtcNow.Date.AddDays(1)).GrossProfitCents);}
 [Fact] public void CheckoutAtomicallyPersistsSalePaymentsAndStock(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,20);var sale=f.Pos.Checkout(f.Manager,f.Input(id,2,2500));Assert.Equal(2000,sale.Sale.TotalCents);Assert.Equal(500,sale.Sale.ChangeCents);Assert.Equal(2000,sale.Payments.Single().AmountCents);Assert.Equal(8,f.Pos.Products(f.Manager).Single().Stock);Assert.Equal(4000,f.Pos.ExpectedCash(f.Manager));using var db=f.Factory.Open();Assert.Single(db.Set<Sale>());Assert.Single(db.Set<SaleItem>());Assert.Equal(2,db.Set<InventoryMovement>().Count());}
 [Fact] public void DuplicateCheckoutRequestReturnsOriginalSaleWithoutDeductingTwice(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);var input=f.Input(id);var a=f.Pos.Checkout(f.Manager,input);var b=f.Pos.Checkout(f.Manager,input);Assert.Equal(a.Sale.Id,b.Sale.Id);Assert.Equal(9,f.Pos.Products(f.Manager).Single().Stock);using var db=f.Factory.Open();Assert.Single(db.Set<Sale>());}
 [Fact] public void FailedCheckoutDoesNotLeaveAnySaleOrStockChange(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);Assert.Throws<DomainException>(()=>f.Pos.Checkout(f.Manager,f.Input(id,2,100)));Assert.Equal(10,f.Pos.Products(f.Manager).Single().Stock);using var db=f.Factory.Open();Assert.Empty(db.Set<Sale>());}
 [Fact] public void FailureAfterAllDatabaseWritesRollsBackEntireCheckout(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);var pos=new PosService(new FaultFactory(f.Factory),f.Security,f.Clock);Assert.Throws<IOException>(()=>pos.Checkout(f.Manager,f.Input(id)));Assert.Equal(10,f.Pos.Products(f.Manager).Single().Stock);using var db=f.Factory.Open();Assert.Empty(db.Set<Sale>());Assert.Empty(db.Set<Payment>());Assert.Single(db.Set<InventoryMovement>());}
 [Fact] public void CardOverpaymentCannotProduceCashChange(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);Assert.Throws<DomainException>(()=>f.Pos.Checkout(f.Manager,f.Input(id) with{Payments=[new Tender("Card",1100)]}));}
 [Fact] public void MixedTenderCashReconciliationUsesNetCashOnly(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,10);var receipt=f.Pos.Checkout(f.Manager,f.Input(id) with{Payments=[new Tender("Card",600),new Tender("Cash",800)]});Assert.Equal(400,receipt.Sale.ChangeCents);Assert.Equal(1400,f.Pos.ExpectedCash(f.Manager));f.Pos.CashInOut(f.Manager,-2,"Paid out");Assert.Equal(1200,f.Pos.ExpectedCash(f.Manager));Assert.Equal(-100,f.Pos.CloseShift(f.Manager,11,"Count discrepancy"));}
 [Fact] public void ASecondOpenShiftOnSingleDrawerIsRejected(){using var f=new Fixture();var e=f.Employee();f.Pos.OpenShift(f.Manager,0);Assert.Throws<DomainException>(()=>f.Pos.OpenShift(e,0));}
 [Fact] public void ManagerApprovalIsPayloadBoundOneTimeAndDoesNotGrantPermission(){using var f=new Fixture();var e=f.Employee();var id=f.Product();f.Pos.OpenShift(e,0);var input=f.Input(id) with{DiscountCents=100};var failure=Assert.Throws<ApprovalRequiredException>(()=>f.Pos.Checkout(e,input));var token=f.Security.Approve(e,"manager","SafePass1234",failure.Permission,failure.Payload,"Customer service");Assert.Throws<DomainException>(()=>f.Pos.Checkout(e,input with{RequestId=Guid.NewGuid(),Approval=token}));var receipt=f.Pos.Checkout(e,input with{Approval=token});Assert.Equal(900,receipt.Sale.TotalCents);Assert.False(f.Security.Can(e,"Sales.ApplyDiscount"));Assert.Throws<DomainException>(()=>f.Pos.Checkout(e,input with{RequestId=Guid.NewGuid(),Approval=token}));using var db=f.Factory.Open();Assert.NotNull(db.Set<ApprovalDecision>().Single().UsedAtUtc);}
 [Fact] public void ForgedManagerFlagCannotBypassEmployeeDiscountThreshold(){using var f=new Fixture();var e=f.Employee();f.Security.Override(f.Manager,e.UserId,"Sales.ApplyDiscount",true);var id=f.Product();f.Pos.OpenShift(e,0);Assert.Throws<ApprovalRequiredException>(()=>f.Pos.Checkout(e with{IsManager=true},f.Input(id) with{DiscountCents=1}));}
 [Fact] public void ExpiredApprovalIsRejected(){using var f=new Fixture();var e=f.Employee();var id=f.Product();var failure=Assert.Throws<ApprovalRequiredException>(()=>f.Pos.AdjustStock(e,id,1,"Count"));var token=f.Security.Approve(e,"manager","SafePass1234",failure.Permission,failure.Payload,"Reviewed");f.Clock.UtcNow=f.Clock.UtcNow.AddMinutes(3);Assert.Throws<DomainException>(()=>f.Pos.AdjustStock(e,id,1,"Count",token));}
 [Fact] public void PartialRefundsCannotExceedQuantityOrPayments(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);var sale=f.Pos.Checkout(f.Manager,f.Input(id,3,3000));var item=sale.Items.Single();f.Pos.Refund(f.Manager,new RefundInput(Guid.NewGuid(),item.Id,1,true,"Returned"));Assert.Equal(8,f.Pos.Products(f.Manager).Single().Stock);f.Pos.Refund(f.Manager,new RefundInput(Guid.NewGuid(),item.Id,2,true,"Returned"));Assert.Throws<DomainException>(()=>f.Pos.Refund(f.Manager,new RefundInput(Guid.NewGuid(),item.Id,1,true,"Excess")));Assert.Equal(0,f.Pos.ExpectedCash(f.Manager));using var db=f.Factory.Open();Assert.Equal(3000,db.Set<Refund>().AsEnumerable().Sum(x=>x.AmountCents));Assert.Equal(3000,db.Set<RefundPayment>().AsEnumerable().Sum(x=>x.AmountCents));}
 [Fact] public void RefundRoundingUsesCumulativeAllocationAndNeverOverRefunds(){using var f=new Fixture();var id=f.Product(0.01m,0m,4);f.Pos.OpenShift(f.Manager,0);var sale=f.Pos.Checkout(f.Manager,f.Input(id,4,4) with{DiscountCents=2});for(int i=0;i<4;i++)f.Pos.Refund(f.Manager,new RefundInput(Guid.NewGuid(),sale.Items.Single().Id,1,true,"Return"));using var db=f.Factory.Open();var refunds=db.Set<Refund>().ToList();Assert.All(refunds,x=>Assert.True(x.AmountCents>=0));Assert.Equal(2,refunds.Sum(x=>x.AmountCents));}
 [Fact] public void DamagedReturnsDoNotReverseCostOfGoodsSold(){using var f=new Fixture();var id=f.Product(10,4);f.Pos.OpenShift(f.Manager,0);var sale=f.Pos.Checkout(f.Manager,f.Input(id));f.Pos.Refund(f.Manager,new RefundInput(Guid.NewGuid(),sale.Items.Single().Id,1,false,"Damaged"));var report=f.Pos.Report(f.Manager,f.Clock.UtcNow.Date,f.Clock.UtcNow.Date.AddDays(1));Assert.Equal(-400,report.GrossProfitCents);Assert.Equal(9,f.Pos.Products(f.Manager).Single().Stock);}
 [Fact] public void EmployeeReportsAreScopedToCurrentCashier(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);f.Pos.Checkout(f.Manager,f.Input(id));f.Pos.CloseShift(f.Manager,10,"");var e=f.Employee();f.Pos.OpenShift(e,0);f.Pos.Checkout(e,f.Input(id));var r=f.Pos.Report(e,f.Clock.UtcNow.Date,f.Clock.UtcNow.Date.AddDays(1));Assert.Single(r.Sales);Assert.All(r.Sales,x=>Assert.Equal(e.UserId,x.UserId));Assert.Throws<DomainException>(()=>f.Pos.SaleItems(e,1));}
 [Fact] public void PurchaseReceivingSupportsPartialQuantitiesWithoutOverReceiving(){using var f=new Fixture();var id=f.Product(10,4,0);var supplier=f.Pos.SaveSupplier(f.Manager,0,"Supplier","","");var purchase=f.Pos.CreatePurchase(f.Manager,supplier,"INV",[new PurchaseLine(id,5,500)]);var item=f.Pos.PurchaseItems(f.Manager).Single();Assert.Equal(purchase,item.PurchaseId);f.Pos.ReceivePurchase(f.Manager,item.Id,2);f.Pos.ReceivePurchase(f.Manager,item.Id,3);Assert.Throws<DomainException>(()=>f.Pos.ReceivePurchase(f.Manager,item.Id,1));Assert.Equal(5,f.Pos.Products(f.Manager).Single().Stock);Assert.Equal(500,f.Pos.Products(f.Manager).Single().CostCents);}
 [Fact] public void InvalidPurchaseForeignKeyRollsBackSavedHeader(){using var f=new Fixture();var supplier=f.Pos.SaveSupplier(f.Manager,0,"Supplier","","");Assert.Throws<DbUpdateException>(()=>f.Pos.CreatePurchase(f.Manager,supplier,"",[new PurchaseLine(999,1,100)]));using var db=f.Factory.Open();Assert.Empty(db.Set<Purchase>());}
 [Fact] public void ImportIsValidatedBeforeMutationAndQuantityIsAdditive(){using var f=new Fixture();var rows=new List<ImportRow>{new(2,"A","000123","Apple",1,2,5,1),new(3,"A","000124","Duplicate",1,2,1,1)};var bad=f.Pos.Import(f.Manager,rows,"skip");Assert.NotEmpty(bad.Errors);Assert.Empty(f.Pos.Products(f.Manager));var ok=f.Pos.Import(f.Manager,[rows[0]],"skip");Assert.Equal(1,ok.Created);var update=f.Pos.Import(f.Manager,[rows[0] with{Quantity=2,Price=3}],"update");Assert.Equal(1,update.Updated);Assert.Equal(7,f.Pos.Products(f.Manager).Single().Stock);Assert.Equal(300,f.Pos.Products(f.Manager).Single().PriceCents);}
 [Fact] public void ExcelRoundTripPreservesTextBarcodes(){using var f=new Fixture();f.Pos.Import(f.Manager,[new ImportRow(2,"X","00000123","Test",1,2,3,1)],"skip");var excel=new ExcelService(f.Security,f.Pos,f.Factory);var path=Path.Combine(f.Folder,"products.xlsx");excel.ExportProducts(f.Manager,path);var data=excel.Read(f.Manager,path,"Inventory");Assert.Equal("00000123",data.Single().Barcode);Assert.Equal(3,data.Single().Quantity);}
 [Fact] public void BackupVerificationAndRestoreRecoverHistoricalData(){using var f=new Fixture();var id=f.Product();var service=new BackupService(f.Factory,f.Security);var backup=Path.Combine(f.Folder,"backup.db");service.Create(f.Manager,backup);f.Pos.AdjustStock(f.Manager,id,2,"Added after backup");Assert.Equal(12,f.Pos.Products(f.Manager).Single().Stock);service.Restore(f.Manager,backup);var session=f.Security.Login("manager","SafePass1234");Assert.Throws<DomainException>(()=>f.Pos.Products(f.Manager));Assert.Equal(10,f.Pos.Products(session).Single().Stock);Assert.NotEmpty(Directory.GetFiles(Path.Combine(f.Folder,"Backups")));}
 [Fact] public void EmployeeCannotBackupOrRestoreAndRestoreRejectsOpenShift(){using var f=new Fixture();var e=f.Employee();var service=new BackupService(f.Factory,f.Security);Assert.Throws<DomainException>(()=>service.Create(e,Path.Combine(f.Folder,"bad.db")));f.Pos.OpenShift(f.Manager,0);Assert.Throws<DomainException>(()=>service.Restore(f.Manager,"anything.db"));}
 [Theory][InlineData(false,14,1026,126)][InlineData(true,14,900,111)]public void TaxAndFixedDiscountCalculationIsExact(bool inclusive,int rate,long expectedTotal,long expectedTax){var lines=new List<SaleItem>{new(){UnitPriceCents=1000,Quantity=1}};var result=PosService.Calculate(lines,100,rate,inclusive);Assert.Equal(expectedTotal,result.Total);Assert.Equal(expectedTax,result.Tax);}
 [Fact] public void DiscountAllocationPreservesEveryCent(){var lines=new List<SaleItem>{new(){UnitPriceCents=33,Quantity=1},new(){UnitPriceCents=33,Quantity=1},new(){UnitPriceCents=34,Quantity=1}};var totals=PosService.Calculate(lines,1,0,false);Assert.Equal(1,lines.Sum(x=>x.DiscountCents));Assert.Equal(99,totals.Total);}

 [Fact] public void SameCheckoutIdWithDifferentPayloadIsRejected(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);var input=f.Input(id);f.Pos.Checkout(f.Manager,input);Assert.Throws<DomainException>(()=>f.Pos.Checkout(f.Manager,input with{Notes="changed"}));}
 [Fact] public void CheckoutRejectsStaleExpectedPrice(){using var f=new Fixture();var id=f.Product();f.Pos.OpenShift(f.Manager,0);var input=f.Input(id) with{Lines=[new CartLine(id,1,null,900)]};Assert.Throws<DomainException>(()=>f.Pos.Checkout(f.Manager,input));using var db=f.Factory.Open();Assert.Empty(db.Set<Sale>());}
 [Fact] public void AuthorizedEmployeeCanEditNameWithoutReadingOrChangingCost(){using var f=new Fixture();var id=f.Product();var e=f.Employee();f.Security.Override(f.Manager,e.UserId,"Products.Edit",true);var product=f.Pos.Products(e).Single();f.Pos.SaveProduct(e,new ProductInput(id,product.SKU,product.Barcode,"New name",0,10,2));Assert.Equal(400,f.Pos.Products(f.Manager).Single().CostCents);Assert.Throws<DomainException>(()=>f.Pos.SaveProduct(e,new ProductInput(id,product.SKU,product.Barcode,"New name",1,10,2)));}
 [Fact] public void ProductPriceOverrideRequiresApproval(){using var f=new Fixture();var id=f.Product();var e=f.Employee();f.Pos.OpenShift(e,0);var input=f.Input(id) with{Lines=[new CartLine(id,1,900,1000)]};var failure=Assert.Throws<ApprovalRequiredException>(()=>f.Pos.Checkout(e,input));Assert.Equal("Sales.OverridePrice",failure.Permission);var token=f.Security.Approve(e,"manager","SafePass1234",failure.Permission,failure.Payload,"Agreed price");Assert.Equal(900,f.Pos.Checkout(e,input with{Approval=token}).Sale.TotalCents);}
 [Fact] public void StockAdjustmentsAlsoCreateAuditRecords(){using var f=new Fixture();f.Product();Assert.Contains(f.Pos.Audit(f.Manager),x=>x.Action=="Inventory.Adjust");}
 [Fact] public void LogoutRevokesSessionAndCannotSpoofAnotherActor(){using var f=new Fixture();var e=f.Employee();var before=f.Pos.Audit(f.Manager).Count(x=>x.Action=="Logout");f.Security.Logout(e with{UserId=f.Manager.UserId});Assert.Equal(before,f.Pos.Audit(f.Manager).Count(x=>x.Action=="Logout"));Assert.Throws<DomainException>(()=>f.Pos.Products(e));}
 [Fact] public void ReturnedStockReentersAtOriginalCostSnapshot(){using var f=new Fixture();var id=f.Product(10,4);f.Pos.OpenShift(f.Manager,0);var sale=f.Pos.Checkout(f.Manager,f.Input(id));var supplier=f.Pos.SaveSupplier(f.Manager,0,"Supplier","","");f.Pos.CreatePurchase(f.Manager,supplier,"",[new PurchaseLine(id,5,800)]);f.Pos.ReceivePurchase(f.Manager,f.Pos.PurchaseItems(f.Manager).Single().Id,5);Assert.Equal(543,f.Pos.Products(f.Manager).Single().CostCents);f.Pos.Refund(f.Manager,new RefundInput(Guid.NewGuid(),sale.Items.Single().Id,1,true,"Returned"));Assert.Equal(533,f.Pos.Products(f.Manager).Single().CostCents);}
 private sealed class FaultFactory(IDbFactory inner):IDbFactory {public IPosDb Open()=>new FaultDb(inner.Open());}
 private sealed class FaultDb(IPosDb inner):IPosDb {private int saves;public IQueryable<T> Set<T>()where T:Entity=>inner.Set<T>();public void Add<T>(T value)where T:Entity=>inner.Add(value);public void Remove<T>(T value)where T:Entity=>inner.Remove(value);public ITransaction Begin()=>inner.Begin();public void Save(){inner.Save();if(++saves==3)throw new IOException("Simulated interruption before transaction commit");}public void Dispose()=>inner.Dispose();}
}
