<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup></PropertyGroup><ItemGroup><ProjectReference Include="../CashierPOS.Core/CashierPOS.Core.csproj" /><ProjectReference Include="../CashierPOS.Application/CashierPOS.Application.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" /><PackageReference Include="ClosedXML" Version="0.105.1" /></ItemGroup></Project>
