using CashierPOS.Core;
using CashierPOS.Application;
using ClosedXML.Excel;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
namespace CashierPOS.Infrastructure;
public sealed class ExcelService(SecurityService security,PosService pos,IDbFactory factory) {
 private static readonly string[] Headers=["SKU","Barcode","ProductName","CostPrice","SellingPrice","Quantity","MinimumStock"];
 public List<string> Worksheets(Session s,string path){securityCheck(s,"Excel.Import");using var wb=new XLWorkbook(path);return wb.Worksheets.Select(x=>x.Name).ToList();}
 public List<string> HeadersIn(Session s,string path,string worksheet){securityCheck(s,"Excel.Import");using var wb=new XLWorkbook(path);return wb.Worksheet(worksheet).Row(1).CellsUsed().Select(x=>x.GetString().Trim()).Where(x=>x!="").ToList();}
 public List<ImportRow> Read(Session s,string path,string worksheet,Dictionary<string,string>? mapping=null){securityCheck(s,"Excel.Import");var file=new FileInfo(path);if(file.Length>20*1024*1024)throw new DomainException("Workbook exceeds the 20 MB limit.");using var wb=new XLWorkbook(path);var ws=wb.Worksheet(worksheet);var columns=ws.Row(1).CellsUsed().ToDictionary(c=>c.GetString().Trim(),c=>c.Address.ColumnNumber,StringComparer.OrdinalIgnoreCase);mapping??=Headers.ToDictionary(x=>x,x=>x);foreach(var h in new[]{"SKU","ProductName","SellingPrice"})if(!mapping.TryGetValue(h,out var target)||!columns.ContainsKey(target))throw new DomainException("Map required column: "+h);foreach(var h in Headers)if(!mapping.ContainsKey(h))mapping[h]="";var rows=new List<ImportRow>();
  string Cell(int r,string h)=>columns.TryGetValue(mapping[h],out var column)?ws.Cell(r,column).GetFormattedString().Trim():"";
  decimal D(int r,string h){if(!columns.TryGetValue(mapping[h],out var column))return 0;var c=ws.Cell(r,column);if(c.DataType==XLDataType.Number)return c.GetValue<decimal>();if(decimal.TryParse(c.GetString(),NumberStyles.Number,CultureInfo.InvariantCulture,out var d))return d;throw new DomainException($"Row {r}: {h} must be numeric.");}
  int I(int r,string h){var d=D(r,h);if(d!=decimal.Truncate(d)||d>int.MaxValue||d<int.MinValue)throw new DomainException($"Row {r}: {h} must be a whole number.");return (int)d;}
  var last=ws.LastRowUsed()?.RowNumber()??1;if(last>10001)throw new DomainException("Import is limited to 10,000 data rows.");for(var r=2;r<=last;r++){if(ws.Row(r).IsEmpty())continue;rows.Add(new ImportRow(r,Cell(r,"SKU"),Cell(r,"Barcode"),Cell(r,"ProductName"),D(r,"CostPrice"),D(r,"SellingPrice"),I(r,"Quantity"),I(r,"MinimumStock")));}return rows;
 }
 public void Template(Session s,string path){securityCheck(s,"Excel.Import");using var wb=new XLWorkbook();var ws=wb.AddWorksheet("Products");for(var i=0;i<Headers.Length;i++)ws.Cell(1,i+1).Value=Headers[i];ws.Column(1).Style.NumberFormat.Format="@";ws.Column(2).Style.NumberFormat.Format="@";ws.Range(1,1,1,Headers.Length).Style.Font.Bold=true;ws.Columns().AdjustToContents();wb.SaveAs(path);}
 public void ExportProducts(Session s,string path){securityCheck(s,"Excel.Export");var data=pos.Products(s,"",true);using var wb=new XLWorkbook();var ws=wb.AddWorksheet("Inventory");string[] hs=["SKU","Barcode","ProductName","SellingPrice","Quantity","MinimumStock","Active","CostPrice"];for(var i=0;i<hs.Length;i++)ws.Cell(1,i+1).Value=hs[i];int r=2;foreach(var p in data){ws.Cell(r,1).Value=p.SKU;ws.Cell(r,2).Value=p.Barcode;ws.Cell(r,3).Value=p.Name;ws.Cell(r,4).Value=Money.Amount(p.PriceCents);ws.Cell(r,5).Value=p.Stock;ws.Cell(r,6).Value=p.MinimumStock;ws.Cell(r,7).Value=p.IsActive;if(p.CostCents!=null)ws.Cell(r,8).Value=Money.Amount(p.CostCents.Value);r++;}ws.Columns().AdjustToContents();wb.SaveAs(path);Audit(s,"Excel.ExportProducts");}
 public void ExportSales(Session s,Report report,string path){securityCheck(s,"Excel.Export");var fresh=pos.Report(s,report.FromUtc,report.ToUtc);using var wb=new XLWorkbook();var ws=wb.AddWorksheet("Sales");string[] hs=["Invoice","DateUtc","CashierId","Total","Discount","Tax"];for(var i=0;i<hs.Length;i++)ws.Cell(1,i+1).Value=hs[i];var r=2;foreach(var v in fresh.Sales){ws.Cell(r,1).Value=v.InvoiceNumber;ws.Cell(r,2).Value=v.CreatedAtUtc;ws.Cell(r,3).Value=v.UserId;ws.Cell(r,4).Value=Money.Amount(v.TotalCents);ws.Cell(r,5).Value=Money.Amount(v.DiscountCents);ws.Cell(r,6).Value=Money.Amount(v.TaxCents);r++;}ws.Columns().AdjustToContents();wb.SaveAs(path);Audit(s,"Excel.ExportSales");}
 private void securityCheck(Session s,string permission){using var db=factory.Open();security.Require(db,s,permission);}
 private void Audit(Session s,string action){using var db=factory.Open();db.Add(new AuditLog{UserId=s.UserId,Action=action,Entity="File"});db.Save();}
}
public sealed class BackupService(SqliteFactory factory,SecurityService security) {
 public string Create(Session s,string destination){using(var db=factory.Open())security.Require(db,s,"Backup.Create");destination=System.IO.Path.GetFullPath(destination);if(destination==factory.Path)throw new DomainException("Backup must use a different file.");if(File.Exists(destination))throw new DomainException("Choose a new backup filename.");Directory.CreateDirectory(System.IO.Path.GetDirectoryName(destination)!);using(var source=new SqliteConnection($"Data Source={factory.Path};Pooling=False"))using(var target=new SqliteConnection($"Data Source={destination};Pooling=False")){source.Open();target.Open();source.BackupDatabase(target);}Verify(destination);using(var db=factory.Open()){db.Add(new BackupHistory{UserId=s.UserId,Path=destination});db.Add(new AuditLog{UserId=s.UserId,Action="Backup.Create",Entity="Database",Details=destination});db.Save();}return destination;}
 public void Restore(Session s,string backup){using(var db=factory.Open()){security.Require(db,s,"Backup.Restore");if(db.Set<CashierShift>().Any(x=>x.ClosedAtUtc==null))throw new DomainException("Close the open shift before restoring.");}backup=System.IO.Path.GetFullPath(backup);if(backup==factory.Path)throw new DomainException("Choose a backup, not the active database.");Verify(backup);
  var safety=System.IO.Path.Combine(System.IO.Path.GetDirectoryName(factory.Path)!,"Backups",$"pre-restore-{DateTime.UtcNow:yyyyMMdd-HHmmss}-{Guid.NewGuid():N}.db");Create(s,safety);
  var temporary=factory.Path+".restore";try{using(var source=new SqliteConnection($"Data Source={backup};Mode=ReadOnly;Pooling=False"))using(var target=new SqliteConnection($"Data Source={temporary};Pooling=False")){source.Open();target.Open();source.BackupDatabase(target);}Verify(temporary);File.Move(temporary,factory.Path,true);using var restored=factory.Open();restored.Add(new AuditLog{Action="Backup.Restore",Entity="Database",Details=$"Backup={backup}; pre-restore={safety}; actor from prior database={s.UserId}"});restored.Save();security.RevokeAllSessions();}finally{if(File.Exists(temporary))File.Delete(temporary);}
 }
 public void Verify(string path){using var c=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=path,Mode=SqliteOpenMode.ReadOnly,Pooling=false}.ToString());c.Open();using var cmd=c.CreateCommand();cmd.CommandText="PRAGMA integrity_check;";if(Convert.ToString(cmd.ExecuteScalar())!="ok")throw new DomainException("Backup integrity check failed.");cmd.CommandText="PRAGMA foreign_key_check;";using(var reader=cmd.ExecuteReader())if(reader.Read())throw new DomainException("Backup contains broken foreign keys.");cmd.CommandText="SELECT MigrationId FROM __EFMigrationsHistory ORDER BY MigrationId";var migrations=new List<string>();using(var reader=cmd.ExecuteReader())while(reader.Read())migrations.Add(reader.GetString(0));using var current=factory.Create();if(!migrations.SequenceEqual(current.Database.GetMigrations()))throw new DomainException("Backup schema version does not match this application.");}
}
